apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: java-app
    app.kubernetes.io/instance: java-app-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: java-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - image: 538648446500.dkr.ecr.us-west-2.amazonaws.com/java-app-reg:latest
          imagePullPolicy: Always
          name: java-app
          ports:
            - containerPort: 3000
