apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: java-app
    app.kubernetes.io/instance: java-app-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: java-app
spec:
  selector:
    app: java-app
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 90
      targetPort: 4000
